/**
 * U6 — the three claims a Node suite cannot make.
 *
 * A real save resumes and the run reaches the results screen; a browser that
 * refuses to store anything warns the player exactly once and keeps playing;
 * and the atlas still searches, filters and selects after being lifted out of
 * the monolith. All three are DOM-and-timing behavior, so they need a browser.
 *
 * The save the first two tests resume is generated by the engine itself rather
 * than hand-written: `isValidRun` replays every stored answer, so a payload
 * this suite invented would be rejected before the game ever saw it. It stops
 * on the first question of the last country the player can afford, with
 * `revealedIndex` already set — exactly what a save captured after an arrival
 * flight looks like — which is what keeps five questions of real play from
 * costing five twelve-second flights.
 *
 * Out of `npm test` for the same reason as `readable-build.spec.ts`: a real
 * Chromium and a real build do not belong in a suite that runs on every save.
 * Run with `npx playwright test`; `npm run test:browser` is U14's to wire up.
 */
import { expect, test, type Page } from '@playwright/test';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';
import { REPO_ROOT, writeReadable } from '../../scripts/build.ts';
import * as Core from '../../src/engine/core.ts';
import type { Country, GameState } from '../../src/engine/types.ts';

test.setTimeout(120_000);

/** Only what these tests read off `window.WorldGeography`, cast at each use. */
interface StatusView {
  phase: string;
  clock: { elapsedMs: number; remainingMs: number; running: boolean; index: number } | null;
}
interface DebugView {
  getState(): GameState | null;
  getView(): string;
  getStatus(): StatusView;
  version: string;
}

const STORAGE_WARNING = 'Prohlížeč nepovoluje ukládání. Po zavření stránky se postup ztratí.';

const countries = JSON.parse(
  readFileSync(join(REPO_ROOT, 'data/build/countries.json'), 'utf8'),
) as Country[];

/**
 * Play wrong answers with the engine until the last affordable country begins.
 *
 * Wrong on purpose: a correct answer scores, ten thousand points buys two more
 * attempts and a flag bonus, and the run would never end.
 */
function endgameSave(): GameState {
  const game = Core.makeGame(
    countries,
    { players: 1, names: ['Tester', 'Hráč 2'], difficulty: 'normal', region: 'all' },
    20260909,
  );
  for (let guard = 0; guard < 400; guard += 1) {
    const question = game.questions[game.index];
    if (question === undefined) break;
    Core.submit(game, (question.correct + 1) % 3, 1000);
    if (game.gameOver || !Core.advance(game, countries)) break;
    const next = game.questions[game.index];
    if (next?.type === 'country' && game.lives[0] === 0) {
      game.revealedIndex = game.index;
      game.clock = null;
      return game;
    }
  }
  throw new Error('the simulated run never reached its last affordable country');
}

let out: string;
let pageUrl: string;
let save: string;

test.beforeAll(async () => {
  out = mkdtempSync(join(tmpdir(), 'wg-state-'));
  const file = join(out, 'index.html');
  await writeReadable(undefined, file);
  pageUrl = pathToFileURL(file).href;
  save = JSON.stringify(endgameSave());
});

test.afterAll(() => {
  rmSync(out, { recursive: true, force: true });
});

/** Answer wrongly through the UI until the game leaves the question phase. */
async function answerWrong(page: Page): Promise<void> {
  await page.waitForFunction(() => {
    const status = (window as unknown as { WorldGeography: DebugView }).WorldGeography.getStatus();
    return status.phase === 'question' && status.clock?.running === true;
  }, null, { timeout: 30_000 });

  const wrong = await page.evaluate(() => {
    const api = (window as unknown as { WorldGeography: DebugView }).WorldGeography;
    const game = api.getState();
    if (game === null) throw new Error('no game');
    const question = game.questions[game.index];
    if (question === undefined) throw new Error('no question');
    return (question.correct + 1) % 3;
  });

  await page.locator(`[data-answer="${String(wrong)}"]`).click();
  await expect(page.locator('#next')).toBeVisible();
  await page.locator('#next').click();
}

test('resumes a real save and plays it through to the results screen', async ({ page }) => {
  await page.addInitScript(
    ([run, audio]) => {
      window.localStorage.setItem('wg.run.v7', run!);
      window.localStorage.setItem('wg.audio.v2', audio!);
    },
    [save, JSON.stringify({ enabled: false })],
  );

  await page.goto(pageUrl);
  await expect(page.locator('#resume')).toBeVisible();
  await page.locator('#resume').click();

  // The five questions of the last country the run could pay for.
  for (let i = 0; i < 5; i += 1) await answerWrong(page);

  await expect(page.locator('#results-view')).toBeVisible();
  await expect(page.locator('#results-view .result-stat').first()).toBeVisible();
  await expect(page.locator('#again')).toBeVisible();

  const view = await page.evaluate(
    () => (window as unknown as { WorldGeography: DebugView }).WorldGeography.getView(),
  );
  expect(view).toBe('results');

  // The run is finished, so the slot is cleared and the record is written.
  const stored = await page.evaluate(() => ({
    run: window.localStorage.getItem('wg.run.v7'),
    record: window.localStorage.getItem('wg.record.v7'),
  }));
  expect(stored.run).toBe('null');
  expect(JSON.parse(stored.record ?? 'null')).toMatchObject({ schemaVersion: 1 });
});

test('warns once about a browser that refuses to store, and stays playable', async ({ page }) => {
  await page.addInitScript(
    ([run]) => {
      window.localStorage.setItem('wg.run.v7', run!);
      window.localStorage.setItem('wg.audio.v2', JSON.stringify({ enabled: false }));
      // Every write from here on fails the way a full quota or a locked-down
      // private window fails: reading still works, storing never does.
      Storage.prototype.setItem = function setItem(): void {
        throw new DOMException('QuotaExceededError', 'QuotaExceededError');
      };
    },
    [save],
  );

  await page.goto(pageUrl);
  // Installed after boot and before the first write, so it counts every reveal.
  await page.evaluate(() => {
    const toast = document.getElementById('toast');
    if (toast === null) throw new Error('no toast element');
    (window as unknown as { __toastShows: number }).__toastShows = 0;
    new MutationObserver(() => {
      if (!toast.hidden) (window as unknown as { __toastShows: number }).__toastShows += 1;
    }).observe(toast, { attributes: true, attributeFilter: ['hidden'] });
  });

  await expect(page.locator('#resume')).toBeVisible();
  await page.locator('#resume').click();

  await expect(page.locator('#toast')).toBeVisible();
  await expect(page.locator('#toast')).toHaveText(STORAGE_WARNING);

  // Still a game: three answers, a running clock, and a question that can be
  // answered. `tickClock` saves once a second, so this is many failed writes.
  await expect(page.locator('.answer-list button.answer')).toHaveCount(3);
  await answerWrong(page);
  await answerWrong(page);

  const shows = await page.evaluate(() => (window as unknown as { __toastShows: number }).__toastShows);
  expect(shows).toBe(1);

  const status = await page.evaluate(
    () => (window as unknown as { WorldGeography: DebugView }).WorldGeography.getStatus(),
  );
  expect(status.phase).toBe('question');
});

test('opens the three dialogs the shell no longer renders itself', async ({ page }) => {
  await page.goto(pageUrl);

  await page.locator('#nav-help').click();
  await expect(page.locator('#dialog')).toBeVisible();
  await expect(page.locator('#dialog-title')).toHaveText('Pět otázek za jeden pokus.');
  await page.locator('#dialog-close').click();

  await page.locator('#data-button').click();
  await expect(page.locator('#dialog-title')).toHaveText('Data mají svůj příběh.');
  // The citation list and the licence block are passed in, not hard-coded.
  await expect(page.locator('#dialog-content .source-item a').first()).toBeVisible();
  await expect(page.locator('#dialog-content .license-details pre')).toContainText('MIT License');
  await expect(page.locator('#export-data')).toBeVisible();
  await page.locator('#dialog-close').click();

  await page.locator('#sound-options').click();
  await expect(page.locator('#dialog-title')).toHaveText('Hudba a zvuky.');
  await page.locator('#audio-volume').fill('30');
  await expect(page.locator('#volume-label')).toHaveText('30 %');

  // The dialog writes through on every change, so the slider *is* the save.
  const stored = await page.evaluate(() => window.localStorage.getItem('wg.audio.v2'));
  expect(JSON.parse(stored ?? 'null')).toMatchObject({ volume: 0.3, schemaVersion: 1 });
});

test('searches, filters and selects in the atlas', async ({ page }) => {
  await page.goto(pageUrl);
  await page.locator('#nav-atlas').click();

  const items = page.locator('#atlas-list .atlas-item');
  await expect(items).toHaveCount(countries.length);
  // The atlas opens on Czechia, and the globe follows the selection.
  await expect(page.locator('#atlas-details h3')).toHaveText('Česko');

  // Search is diacritic-insensitive: `normalize` strips the accents first.
  await page.locator('#atlas-search').fill('japon');
  await expect(items).toHaveCount(1);
  await expect(items.first()).toContainText('Japonsko');

  await page.locator('#atlas-search').fill('');
  await page.locator('#atlas-region').selectOption('Europe');
  await expect(items).toHaveCount(countries.filter((c) => c.region === 'Europe').length);

  await page.locator('[data-country="PL"]').click();
  await expect(page.locator('#atlas-details h3')).toHaveText('Polsko');
  await expect(page.locator('#world-caption .caption-title')).toHaveText('Polsko');
  await expect(page.locator('[data-country="PL"]')).toHaveAttribute('aria-pressed', 'true');

  // The filter survives a selection, and the search box keeps its value.
  await expect(items).toHaveCount(countries.filter((c) => c.region === 'Europe').length);

  const view = await page.evaluate(
    () => (window as unknown as { WorldGeography: DebugView }).WorldGeography.getView(),
  );
  expect(view).toBe('atlas');
});
