/**
 * U11 — the catalog, the plurals, the detection, and the switcher.
 *
 * The unit's whole risk is a silent one: two hundred Czech literals move out of
 * the views into `src/i18n/cs.ts`, and a key that resolves to the wrong value
 * still renders, still typechecks and still looks like Czech. So the first
 * thing here is not a unit test at all — it renders every screen and compares
 * the markup against `views-cs-golden.json`, captured from the build before the
 * sweep began. Nothing else in this file matters if that one is red.
 *
 * The fixture is an oracle, not a snapshot to be refreshed: regenerating it to
 * make this pass would delete the only evidence the sweep was faithful. It is
 * regenerated by `node scripts/capture-views.ts`, and only when a Czech string
 * is *meant* to change.
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { installApp, type Harness } from '../helpers/app-harness.ts';
import { captureViews } from '../helpers/views-golden.ts';
import { VIEWS_FIXTURE } from '../../scripts/capture-views.ts';
import { plural } from '../../src/i18n/plurals.ts';
import * as Core from '../../src/engine/core.ts';
import { questionBundle } from '../../src/i18n/questions.ts';
import { store } from '../../src/app/state.ts';
import { loadRun, loadSettings } from '../../src/app/storage.ts';
import { nextLocale, renderLanguage, renderView, switchLanguage } from '../../src/app/main.ts';
import { startGame } from '../../src/app/views/home.ts';
import { pointText, seconds } from '../../src/app/dom.ts';
import { BASELINE_ROOT } from '../helpers/load-baseline.ts';
import type { GameState } from '../../src/engine/types.ts';
import { detectLocale, locale, setLocale, t, type CatalogKey } from '../../src/i18n/index.ts';
import { cs } from '../../src/i18n/cs.ts';
import { en } from '../../src/i18n/en.ts';

let app: Harness;
beforeEach(() => { app = installApp(); });
afterEach(() => { app.restore(); setLocale('cs'); });

const SRC = fileURLToPath(new URL('../../src', import.meta.url));

const golden = (): Record<string, string> =>
  JSON.parse(readFileSync(VIEWS_FIXTURE, 'utf8')) as Record<string, string>;

/**
 * The Czech that is *meant* to be different, and why.
 *
 * U11 step 4: move the literals, but fix the plural agreement rather than
 * transcribing it. v7 wrote the genitive flat at the sites below, so the game
 * told a player with one attempt left that they had "1 pokusů". Each entry is
 * applied to the golden fixture before the comparison, which means an
 * undeclared change still fails and a declared one has to be exactly this
 * change and no other.
 */
const DECLARED_COPY_CHANGES: readonly { from: string; to: string; why: string }[] = [
  {
    from: 'Pokračovat · otázka 2 · 4 pokusů',
    to: 'Pokračovat · otázka 2 · 4 pokusy',
    why: 'the resume button wrote the genitive for every count; four takes the `few` form',
  },
  {
    from: 'Pokračovat · otázka 2 · 4 / 1 pokusů',
    to: 'Pokračovat · otázka 2 · pokusy 4 / 1',
    why:
      'two players have two counts and no single noun can agree with both, so the duel ' +
      'form puts the word first and leaves the numbers uninflected',
  },
  {
    from: '1 správných odpovědí z 1.',
    to: '1 správná odpověď z 1.',
    why: 'the results subtitle wrote the genitive; one answer takes the nominative singular',
  },
  {
    from: '1 navštívených zemí',
    to: '1 navštívená země',
    why: 'the timing summary wrote the genitive; one country takes the nominative singular',
  },
  {
    from: '1 odpovědí · +2 pokusů z bodů a vlajek',
    to: '1 odpověď · +2 pokusy z bodů a vlajek',
    why: 'the duel block wrote both nouns in the genitive; one answer and two attempts agree differently',
  },
];

const declared = (html: string): string => {
  let out = html;
  for (const change of DECLARED_COPY_CHANGES) out = out.split(change.from).join(change.to);
  return out;
};

describe('the Czech a player reads', () => {
  it('is what every screen printed before the catalog existed', async () => {
    const before = golden();
    const now = await captureViews(app);

    // Compared key by key rather than as one object: a whole-object mismatch
    // prints 190 KB of markup and names nothing.
    expect(Object.keys(now)).toEqual(Object.keys(before));
    for (const [name, html] of Object.entries(before)) {
      expect({ [name]: now[name] }).toEqual({ [name]: declared(html) });
    }
  });

  it('declares only changes the fixture actually contains', () => {
    // A declared change nobody applies is a licence left lying around: it would
    // let a future edit to that exact string pass unnoticed.
    const all = Object.values(golden()).join('\n');
    expect(DECLARED_COPY_CHANGES.filter((change) => !all.includes(change.from))).toEqual([]);
  });
});

describe('plural categories', () => {
  it('counts attempts the way Czech counts them', () => {
    // The bug this replaces: ten call sites wrote `${n} pokusů` flat, which is
    // the genitive plural and is wrong for every n from 1 to 4 — the shipped
    // game says "1 pokusů" on the last attempt a player has.
    const attempts = { one: 'pokus', few: 'pokusy', many: 'pokusu', other: 'pokusů' };
    expect([0, 1, 2, 4, 5, 11].map((n) => plural('cs', n, attempts))).toEqual([
      'pokusů', 'pokus', 'pokusy', 'pokusy', 'pokusů', 'pokusů',
    ]);
  });

  it('counts attempts the way English counts them', () => {
    const attempts = { one: 'attempt', other: 'attempts' };
    expect([0, 1, 2, 5].map((n) => plural('en', n, attempts))).toEqual([
      'attempts', 'attempt', 'attempts', 'attempts',
    ]);
  });

  it('falls back to `other` for a category a locale never asks for', () => {
    // English never selects `few`, and Czech `many` only appears for decimals;
    // a catalog entry is allowed to leave either out.
    expect(plural('cs', 1.5, { one: 'pokus', other: 'pokusů' })).toBe('pokusů');
  });
});

describe('locale detection', () => {
  it('takes the first supported primary subtag the browser offers', () => {
    expect(detectLocale(['cs-CZ', 'en'])).toBe('cs');
    expect(detectLocale(['sk', 'cs', 'en'])).toBe('cs');
    expect(detectLocale(['en-GB'])).toBe('en');
  });

  it('falls back to English for a browser that asks for neither', () => {
    // Not to Czech: the fallback is for a reader who has told the browser they
    // read something else, and English is the likelier second language of the
    // two this game speaks.
    expect(detectLocale(['de', 'fr'])).toBe('en');
    expect(detectLocale([])).toBe('en');
  });

  it('lets a stored choice override the browser', () => {
    expect(detectLocale(['en-US'], 'cs')).toBe('cs');
    expect(detectLocale(['cs-CZ'], 'en')).toBe('en');
  });

  it('ignores a stored value that is not a locale this game has', () => {
    expect(detectLocale(['cs-CZ'], 'de')).toBe('cs');
    expect(detectLocale(['de'], 42)).toBe('en');
  });
});

describe('the catalog', () => {
  it('says the same things in both languages', () => {
    expect(Object.keys(en).sort()).toEqual(Object.keys(cs).sort());
  });

  it('gives every count-dependent entry the same shape in both', () => {
    const shape = (value: unknown): string => (typeof value === 'string' ? 'string' : 'plural');
    const mismatched = Object.keys(cs).filter(
      (key) => shape(cs[key as CatalogKey]) !== shape(en[key as CatalogKey]),
    );
    expect(mismatched).toEqual([]);
  });

  it('interpolates the parameters a template names', () => {
    setLocale('cs');
    expect(t('game.turn', { name: 'Ada' })).toBe('Na tahu: Ada');
  });

  it('selects the plural form the count implies, in the active locale', () => {
    setLocale('cs');
    expect(t('game.attempts', { count: 1 })).toBe('1 pokus');
    expect(t('game.attempts', { count: 3 })).toBe('3 pokusy');
    expect(t('game.attempts', { count: 7 })).toBe('7 pokusů');
    setLocale('en');
    expect(t('game.attempts', { count: 1 })).toBe('1 attempt');
    expect(t('game.attempts', { count: 7 })).toBe('7 attempts');
  });
});

describe('the switcher', () => {
  it('offers the language it is not showing, as a list rather than a flag', () => {
    setLocale('cs');
    expect(nextLocale()).toBe('en');
    setLocale('en');
    expect(nextLocale()).toBe('cs');
  });

  it('names itself in the language it switches to, with a matching lang', () => {
    // A screen reader that meets `Angličtina` reads a Czech word to a reader
    // who has just been offered English. The name belongs to the target, and
    // so does the `lang` on the element carrying it — an `aria-label` could
    // not carry one.
    setLocale('cs');
    renderLanguage();

    expect(app.el('language').innerHTML).toContain('lang="en">English</span>');
    expect(app.el('language').innerHTML).toContain('>EN<');
  });

  it('re-renders the current screen and restates the document language', () => {
    renderView('atlas');
    const before = app.el('side-panel').innerHTML;

    switchLanguage('en');

    expect(locale()).toBe('en');
    expect(app.el('side-panel').innerHTML).not.toBe(before);
    expect(app.el('side-panel').innerHTML).toContain('Atlas of the world');
    expect(document.documentElement.lang).toBe('en');
  });

  it('puts the focus back on itself, which the re-render just destroyed', () => {
    renderView('home');
    const focusesBefore = app.el('language').focuses;

    switchLanguage('en');

    expect(app.el('language').focuses).toBe(focusesBefore + 1);
  });

  it('announces the new language once, in the new language', () => {
    renderView('home');

    switchLanguage('en');

    expect(app.el('toast').textContent).toBe('Language: English');
    expect(app.el('toast').hidden).toBe(false);
  });

  it('remembers the choice, so detection does not run again', () => {
    renderView('home');

    switchLanguage('en');

    expect(loadSettings().lang).toBe('en');
    expect(detectLocale(['cs-CZ'], loadSettings().lang)).toBe('en');
  });
});

describe('the switcher during a run', () => {
  const startRun = (): void => {
    store.game = Core.makeGame(app.countries, {
      players: 1, names: ['Ada', 'Grace'], difficulty: 'normal', region: 'all',
    }, questionBundle(), 20260915);
    store.view = 'game';
  };

  it('is disabled, and says why in whichever language is on screen', () => {
    // A run bakes its question strings at creation. Switching mid-run would put
    // a Czech prompt above English options, which is the defect KTD13 names.
    startRun();
    setLocale('cs');
    renderLanguage();
    expect((app.el('language') as unknown as { disabled: boolean }).disabled).toBe(true);
    expect(app.el('language').title).toContain('rozehrané hry');

    setLocale('en');
    renderLanguage();
    expect(app.el('language').title).toContain('game in progress');
  });

  it('refuses to switch even if something calls it directly', () => {
    startRun();
    setLocale('cs');

    switchLanguage('en');

    expect(locale()).toBe('cs');
  });

  it('is enabled again once the run is over', () => {
    startRun();
    store.game!.completed = true;
    renderLanguage();

    expect((app.el('language') as unknown as { disabled: boolean }).disabled).toBe(false);
  });
});

describe('a saved run and the language it was written in', () => {
  const v7Save = (): GameState => {
    const raw = JSON.parse(
      readFileSync(join(BASELINE_ROOT, 'runs', 'mid-country.json'), 'utf8'),
    ) as GameState & { lang?: unknown };
    delete raw.lang;
    return raw;
  };

  it('resumes a real v7 save as Czech and pins the session to it', () => {
    // The save predates the switcher, so it can only be Czech — and the reader
    // may well be on an English browser. Dropping it would cost a real player
    // a real run over a field that was never written.
    setLocale(detectLocale(['en-US']));
    expect(locale()).toBe('en');
    app.storage.set('wg.run.v7', JSON.stringify(v7Save()));

    const run = loadRun(app.countries, app.byCode);

    expect(run).not.toBeNull();
    expect(run!.lang).toBe('cs');
  });

  it('refuses a run written in the other language', () => {
    const czech = { ...v7Save(), lang: 'cs' };
    app.storage.set('wg.run.v7', JSON.stringify(czech));

    setLocale('cs');
    expect(loadRun(app.countries, app.byCode)).not.toBeNull();
    setLocale('en');
    expect(loadRun(app.countries, app.byCode)).toBeNull();
  });

  it('stamps a new run with the language it was built in', () => {
    setLocale('en');
    renderView('home');
    startGame();

    expect(store.game?.lang).toBe('en');
  });
});

describe('formatting follows the reader', () => {
  it('writes numbers with the separator the language uses', () => {
    setLocale('cs');
    // Czech groups with a narrow no-break space, not an ordinary one — which is
    // exactly the kind of detail a hand-rolled formatter gets wrong.
    expect(pointText(1234567).replace(/\s/gu, ' ')).toBe('1 234 567');
    expect(seconds(1450)).toBe('1,5');
    setLocale('en');
    expect(pointText(1234567)).toBe('1,234,567');
    expect(seconds(1450)).toBe('1.5');
  });

  it('sorts the atlas by the language\'s own collation', () => {
    // Czech sorts `ch` after `h`, which no English collator does; the atlas
    // list is the one place a reader would notice.
    const names = ['Chile', 'Itálie', 'Honduras'];
    setLocale('cs');
    expect([...names].sort((a, b) => a.localeCompare(b, locale()))).toEqual(['Honduras', 'Chile', 'Itálie']);
    setLocale('en');
    expect([...names].sort((a, b) => a.localeCompare(b, locale()))).toEqual(['Chile', 'Honduras', 'Itálie']);
  });

  it('names the quiz themes in the active language', () => {
    setLocale('cs');
    expect(t('theme.02')).toBe('Skrytý signál');
    setLocale('en');
    expect(t('theme.02')).toBe('Hidden Signal');
  });
});

describe('the sweep is complete', () => {
  /** Every `.ts` under `src/`, with the catalog itself left out. */
  function sources(dir: string, into: string[] = []): string[] {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const path = join(dir, entry.name);
      if (entry.isDirectory()) sources(path, into);
      else if (entry.name.endsWith('.ts')) into.push(path);
    }
    return into;
  }

  /** A run of letters containing at least one that only Czech writes. */
  const CZECH_WORD = /[\p{L}]*[áčďéěíňóřšťúůýžÁČĎÉĚÍŇÓŘŠŤÚŮÝŽ][\p{L}]*/gu;

  /**
   * Comments are not user-visible, and they are where the reasoning lives.
   *
   * Half the value of this tree is in comments explaining what a Czech string
   * used to say and why it changed; a rule that banned the word "pokusů" from
   * the sentence explaining the plural bug would delete the explanation to
   * satisfy the scanner.
   */
  const withoutComments = (text: string): string =>
    text.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/(^|[^:])\/\/[^\n]*/g, '$1 ');

  /**
   * What is still allowed to be Czech outside the catalog.
   *
   * One file is left, and it is one line of it: `clock.ts` throws a Czech
   * `RangeError` at a programmer who passed a bad argument, which no player can
   * reach. `core.ts` came off this list in U12 — question generation moved onto
   * a locale bundle and the engine kept nothing, which is asserted below rather
   * than assumed. Listing the file rather than skipping "anything that still
   * has Czech in it" is what keeps the exception from quietly widening.
   */
  const DECLARED_CZECH: readonly string[] = ['src/engine/clock.ts'];

  it('leaves no Czech word in src/ outside the catalog', () => {
    const offenders: string[] = [];
    for (const file of sources(SRC)) {
      const relative = file.slice(SRC.length + 1);
      if (relative.startsWith('i18n/') || DECLARED_CZECH.includes(`src/${relative}`)) continue;
      const words = [...withoutComments(readFileSync(file, 'utf8')).matchAll(CZECH_WORD)].map((m) => m[0]);
      if (words.length > 0) offenders.push(`src/${relative}: ${[...new Set(words)].join(', ')}`);
    }
    expect(offenders).toEqual([]);
  });

  it('is not a vacuous scan', () => {
    // The pattern has to find Czech where Czech is still expected, or an empty
    // result above would mean the regex, not the sweep. The question bundle is
    // where the engine's two hundred Czech literals went, so it is the honest
    // anchor now.
    const questions = readFileSync(join(SRC, 'i18n/questions.cs.ts'), 'utf8');
    expect([...questions.matchAll(CZECH_WORD)].length).toBeGreaterThan(50);
    expect([...readFileSync(join(SRC, 'i18n/cs.ts'), 'utf8').matchAll(CZECH_WORD)].length)
      .toBeGreaterThan(200);
  });

  it('leaves the engine with no language of its own', () => {
    // U12's claim, stated directly rather than inferred from the list above:
    // there is no Czech left in `core.ts` at all — not in a prompt, not in an
    // explanation, not in a throw a player can be shown.
    const engine = readFileSync(join(SRC, 'engine/core.ts'), 'utf8');
    expect([...engine.matchAll(CZECH_WORD)].map((m) => m[0])).toEqual([]);
  });

  it('keeps the template readable before the bundle runs', () => {
    // The static chrome is translated in place, so the markup still ships the
    // Czech: a reader who gets the HTML and not the script sees a page, and
    // `translateChrome` needs a key on every element it has to reach.
    const template = readFileSync(join(SRC, 'index.template.html'), 'utf8');
    const marked = [...template.matchAll(/data-i18n(?:-label|-title)?="([^"]+)"/g)].map((m) => m[1]!);

    expect(marked.length).toBeGreaterThan(15);
    for (const key of marked) expect(Object.keys(cs)).toContain(key);
  });
});

describe('a question is never half-translated', () => {
  it('cannot reach a screen whose run was written in the other language', () => {
    // The two halves of KTD13's defect, stated together: the switcher refuses
    // while a run is live, and a run that somehow survived into the other
    // language is refused on the way back in. There is no third path — a
    // question's prompt, options and explanation are written once, at
    // creation, from one catalog.
    setLocale('cs');
    renderView('home');
    startGame();
    const czech = store.game!;
    expect(czech.lang).toBe('cs');

    switchLanguage('en');
    expect(locale()).toBe('cs');

    app.storage.set('wg.run.v7', JSON.stringify(czech));
    setLocale('en');
    expect(loadRun(app.countries, app.byCode)).toBeNull();
  });
});
